# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    #
    #    serializer:
    #        name_converter: 'serializer.name_converter.camel_case_to_snake_case'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Domain/User/Entity,Domain/Card/Entity, Domain/Deck/Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    #BUNDLES
    Lexik\Bundle\JWTAuthenticationBundle\Security\Http\Authentication\AuthenticationSuccessHandler:
        autowire: true
    Gesdinet\JWTRefreshTokenBundle\Service\RefreshToken:
        alias: "gesdinet.jwtrefreshtoken"

    #EVENT
    App\Domain\User\Events\AuthenticationSuccessListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
    App\Domain\User\Events\AuthenticationFailureListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onAuthenticationFailureResponse }
    App\Domain\User\Events\JWTCreatedListener:
        arguments: [ '@request_stack' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    App\Domain\User\Events\HashPasswordListener:
        tags:
            - { name: doctrine.event_subscriber }
    App\Event\HTTPExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    #CUSTOM SERVICE
    App\Service\TwigService: ~
    App\Service\MailService\MailSenderService: ~
    App\Service\MailService\MailBuilderService: ~
    App\Service\SerializeService: ~
    App\Service\ValidateService: ~
    App\Domain\User\UserRepository: ~
    App\Domain\User\Service\TokenService: ~

    #VALIDATORS
    validator.unique.uniqueuser:
        class: App\Validator\UniqueEntityConstraint\UniqueEntityValidator
        tags:
            - { name: validator.constraint_validator, alias: UniqueEntity }
    validator.unique.existinguser:
        class: App\Validator\ExistEntityConstraint\ExistEntityValidator
        tags:
            - { name: validator.constraint_validator, alias: ExistEntity }
